name: ci

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        docker-file:
          - path: terratest/1.5.6
            tags: "controlla/terratest:1.5.6"
          - path: circleci/php/7.4
            tags: "controlla/circleci:php-7.4"
          - path: circleci/php/8.1
            tags: "controlla/circleci:php-8.1"
          - path: controlla/php/7.4
            tags: "controlla/controlla:php-7.4"
          - path: controlla/php/7.4/node
            tags: "controlla/controlla:php-7.4-node"
          - path: controlla/php/8.0
            tags: "controlla/controlla:php-8.0"
          - path: controlla/php/8.0/node
            tags: "controlla/controlla:php-8.0-node"
          - path: controlla/php/8.1
            tags: "controlla/controlla:php-8.1"
          - path: controlla/php/8.1/node
            tags: "controlla/controlla:php-8.1-node"
          - path: controlla/ruby/2.5
            tags: "controlla/controlla:ruby-2.5"
          - path: controlla/ruby/2.5/node
            tags: "controlla/controlla:ruby-2.5-node"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: controlla/controlla
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          context: ./${{ matrix.docker-file.path }}
          file: ./${{ matrix.docker-file.path }}/Dockerfile
          tags: ${{ matrix.docker-file.tags }}
          labels: ${{ matrix.docker-file.tags }}